[project]
name = "youtube-auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client>=2.185.0",
    "oauth2client>=4.1.3",
]
