[project]
name = "text-to-audio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.40",
    "fastmcp>=2.12.4",
    "google-cloud-texttospeech>=2.31.0",
    "openai>=2.0.1",
]
